### ISSUE TITLE
Program náhodne zmrzne kvôli NoSuchElementException in "Thread-0"

### ISSUE THREAD

**Issue by domcouhrik** [infjava/shapesge#10]
Celý popis chyby:
```
Exception in thread "Thread-0" java.util.NoSuchElementException
	at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:361)
	at java.base/java.util.ArrayDeque.pop(ArrayDeque.java:592)
	at fri.shapesge.engine.GameEventDispatcher.doEvents(GameEventDispatcher.java:35)
	at fri.shapesge.engine.GameLoop.run(GameLoop.java:32)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```
Program do bodu, kedy je chyba vyhodená, funguje normálne. Akonáhle nastane chyba, program zmrzne, ale nespadne. Po minimalizovaní a refocusnutí ostanie iba biela obrazovka.
Konfigurácia sbge.ini pre program vyhadzujúci túto chybu:
```
[Window]
Width = 1920
Height = 1080
Title = REDACTED
Background = #666666
FPS = 300
ShowInfo = true
Fullscreen = true
OnClose = exit

[Shapes]
ImageSource = file

[Colors]
white = #FFFFFF
grey = #757575
black = #000000
neonRed = #ff0000
neonLime = #00ff00
neonYellow = #ffea21
orange = #ffa200
baseDeckAyuna = #d4263b
baseDeckAyumi = #389c56
baseDeckYumio = #175c9d

[Mouse]
hover = move
select = pressed LEFT
context = pressed MIDDLE

[Timers]
animate = 3
```

**Comment by domcouhrik** [comment]
Did a minor inspection on this, it seeems when `GameEventDispatcher.doEvents()` calls `this.eventQueue.pop()` to the `ArrayDeque eventQueue`, the result will (somehow) be a `null` element (which causes `pop()` to throw `NoSuchElementException`).

Catching this exception and ignoring it only results in the subsequent `event` being `null`, which causes `GameEventDispatcher.sendMessage(event)` to throw a `NullPointerException`.

I will test a hotfix for this, which is:
```java
public synchronized void doEvents() {
        while (!this.eventQueue.isEmpty()) {
            QueuedEvent event = this.eventQueue.pollFirst();// Replaced pop() will pollFirst(), which will return null instead of throwing NoSuchElementException
            this.sendMessage(event);
        }
    }

    private void sendMessage(QueuedEvent event) {
        for (Object target : this.targets) {
            try {
                Method method = target.getClass().getMethod(event.getMessage(), event.getParameterTypes());
                method.invoke(target, event.getParameterValues());
            } catch (NullPointerException | NoSuchMethodException e) { // Added NullPointerException to this catch clause, which will skip processing null events
                // do nothing here
            } catch (SecurityException | IllegalArgumentException | IllegalAccessException |
                     InvocationTargetException e) {
                //noinspection CallToPrintStackTrace
                e.printStackTrace();
            }
        }
    }
```

It should be noted that testing this will be pretty time-consuming as I've been trying to reproduce the issue for 40 minutes (on the release 2.0.4 version) with the issue only occuring _once_.

**Comment by domcouhrik** [comment]
The hotfix is now live in [a separate branch](https://github.com/CombiCraft/shapesge/tree/patch-thread-run-exception). It has not been pushed as a Pull Request here yet, as I'd like to test it more thoroughly before submitting.
